# Generated by Django 3.1.4 on 2020-12-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
